const products = [
  {
    id: 'SMXMXMW000039',
    name: 'Mặt dây chuyền Bạc đính đá Silver True Love',
    price: '545.000',
    size: [9, 10, 11, 12, 13, 14],
    status: true,
    trademark: 'Silver',
    main_stone: 'Xoàn mỹ',
    main_color_stone: '#FFFF00',
    shape: 'Tròn',
    sex: 0,
    weight: 6.99,
    description:
      'Được hoàn thiện vẻ đẹp duy mỹ bởi những viên đá lấp lánh đính thủ công lên từng mảnh trang sức, chiếc mặt dây chuyền được chế tác từ chất liệu bạc cao cấp 92.5 kết hợp cùng sự lấp lánh của những viên đá màu trắng, tựa như đóa hoa bừng nở trên bề mặt một cách mỹ miều và tinh tế.',
    images: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/118/smxmxmw000039-mat-day-chuyen-bac-dinh-da-pnjsilver-1.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/118/smxmxmw000039-mat-day-chuyen-bac-dinh-da-pnjsilver-2.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/118/smxmxmw000039-mat-day-chuyen-bac-dinh-da-pnjsilver-3.png',
    ],
  },
  {
    id: 'SBXMZTW000003',
    name: 'Bông tai bạc đính đá Silver Aura',
    price: '795.000',
    size: [9, 10, 11, 12, 13],
    status: true,
    trademark: 'Silver',
    main_stone: 'Diamond',
    main_color_stone: 'Trắng',
    shape: 'Tròn',
    sex: 0,
    weight: 12.5,
    description:
      'Sở hữu thiết kế có kiểu dáng hình ngôi sao không chỉ kết hợp đính đá nhỏ đính một cách tinh tế mà còn nổi bật với phiên bản cá tính, đôi khuyên tai Silver mang vẻ đẹp vừa thời trang vừa năng động, tô điểm thêm nét xinh yêu cho nàng.',
    images: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/70/sbxmztw000003-bong-tai-bac-dinh-da-pnjsilver-aura-01.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/71/sbxmztw000003-bong-tai-bac-dinh-da-pnjsilver-aura.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/71/sbxmztw000003-bong-tai-bac-dinh-da-pnjsilver-aura-05.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/71/sbxmztw000003-bong-tai-bac-dinh-da-pnjsilver-aura-04.jpg',
    ],
  },
  {
    id: 'SNXMXMW000056',
    name: 'Nhẫn bạc đính đá Silver Xmas',
    price: '645.000',
    size: [11, 12],
    status: true,
    trademark: 'PNJSilverJ',
    main_stone: 'Xoàn mỹ',
    main_color_stone: 'Trắng',
    shape: 'Tròn',
    sex: 0,
    weight: 4.78417,
    description:
      'Nhẫn bạc được thiết kế tận dụng tối đa sự tinh tế của shape đá chữ nhật, sắp xếp 1 cách hài hòa cùng với viên đá tròn tạo thành 1 tổng thể thống nhất, như những khung cửa sổ tràn ngập ánh sáng. Hãy làm cho những ngày lễ trở nên đặc biệt hơn với những tác phẩm mới trong BST Anthology of Light từ PNJ.',
    images: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/117/snxmxmw000056-nhan-bac-dinh-da-pnjsilver-xmas-1.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/117/snxmxmw000056-nhan-bac-dinh-da-pnjsilver-xmas-2.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/117/snxmxmw000056-nhan-bac-dinh-da-pnjsilver-xmas-3.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/117/snxmxmw000056-nhan-bac-dinh-da-pnjsilver-xmas-4.png',
    ],
  },
  {
    id: 'SCXMZTW000003',
    name: 'Dây cổ Bạc đính đá STYLE By Aura',
    price: '878.500',
    size: [9, 10, 11, 12, 13],
    status: true,
    trademark: 'Disney',
    main_stone: 'Diamond',
    main_color_stone: '#FFFF00',
    shape: 'Tròn',
    sex: 0,
    weight: 2.6,
    description:
      'Bằng việc kết hợp chất liệu bạc cao cấp cùng đá đính một cách tinh tế, sợi dây cổ bạc chính là điểm nhấn nổi bật, tô điểm thêm vẻ đẹp thanh lịch và duyên dáng cho nàng. Không quá cầu kỳ cũng không quá phô trương, dây cổ bạc của Silver sẽ giúp các cô gái đẹp tinh tế trong từng khoảnh khắc.',
    images: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/70/scxmztw000003-day-co-bac-dinh-da-pnjsilver-aura.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/71/scxmztw000003-day-co-bac-dinh-da-pnjsilver-aura-03.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/70/scxmztw000003-day-co-bac-dinh-da-pnjsilver-aura-1.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/71/gcxmztw000003-day-co-bac-dinh-da-pnjsilver-aura-04.jpg',
    ],
  },
  {
    id: 'GMDDDDH000048',
    name: 'Mặt dây chuyền Kim Cương Vàng 14K True Love',
    price: '10.013.000',
    size: [],
    status: true,
    trademark: 'Disney|PNJ',
    main_stone: 'Diamond',
    main_color_stone: '#FFFF00',
    shape: 'Tròn',
    sex: 0,
    weight: 2.6,
    description:
      'Kim cương vốn là món trang sức mang đến niềm kiêu hãnh và cảm hứng thời trang bất tận. Sở hữu riêng cho mình món trang sức kim cương chính là điều mà ai cũng mong muốn. Chiếc nhẫn được chế tác từ vàng 14K cùng điểm nhấn kim cương với 57 giác cắt chuẩn xác, tạo nên món trang sức đầy sự sang trọng và đẳng cấp',
    images: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/120/gmddddh000048-mat-day-chuyen-kim-cuong-vang-14k-pnj-01.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/120/gmddddh000048-mat-day-chuyen-kim-cuong-vang-14k-pnj-02.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/120/gmddddh000048-mat-day-chuyen-kim-cuong-vang-14k-pnj-03.pngg',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/120/gmddddh000048-mat-day-chuyen-kim-cuong-vang-14k-pnj-4.jpg',
    ],
  },
  {
    id: 'XMXMW000038',
    name: 'Dây cổ bạc đính đá Silver Xmas',
    price: '855.000',
    size: [42],
    status: true,
    trademark: 'PNJSilver',
    main_stone: 'Xoàn mỹ',
    main_color_stone: 'Trắng',
    sex: 0,
    weight: 0,
    description:
      'Dây cổ bạc được lấy cảm hứng từ những bông hoa tuyết nhưng dùng cách thể hiện hiện đại hơn bằng cách phối trộn shape đá vuông & chữ nhật, tạo cảm giác mới mẻ hơn cho những icon tưởng như đã quá quen thuộc',
    images: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/115/scxmxmw000038-day-co-bac-dinh-da-pnjsilver-xmas-1.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/115/scxmxmw000038-day-co-bac-dinh-da-pnjsilver-xmas-2.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/115/scxmxmw000038-day-co-bac-dinh-da-pnjsilver-xmas-3.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/115/scxmxmw000038-day-co-bac-dinh-da-pnjsilver-xmas-4.png',
    ],
  },
  {
    id: 'SMZTXMK000122',
    name: 'Mặt dây chuyền bạc đính đá Silver',
    price: '425.000',
    size: [42],
    status: true,
    trademark: 'PNJSilver',
    main_stone: '',
    main_color_stone: 'Trắng',
    sex: 0,
    weight: 0,
    description: '',
    images: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/91/smztxmk000122-mat-day-chuyen-bac-dinh-da-pnjsilver.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/91/smztxmk000122-mat-day-chuyen-bac-dinh-da-pnjsilver-01.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/91/smztxmk000122-mat-day-chuyen-bac-dinh-da-pnjsilver-02.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/91/smztxmk000122-mat-day-chuyen-bac-dinh-da-pnjsilver-03.jpg',
    ],
  },
  {
    id: 'SMZTXMK000126',
    name: 'Mặt dây chuyền bạc đính đá Silver Fantasia',
    price: '475.000',
    size: [42],
    status: true,
    trademark: 'PNJSilver',
    main_stone: 'Sythetic',
    main_color_stone: 'Trắng',
    shape: 'Tròn',
    sex: 0,
    weight: 0,
    description: '',
    images: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/93/smztxmk000126-mat-day-chuyen-bac-dinh-da-pnjsilver-fantasia.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/93/smztxmk000126-mat-day-chuyen-bac-dinh-da-pnjsilver-fantasia-1.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/93/smztxmk000126-mat-day-chuyen-bac-dinh-da-pnjsilver-fantasia-2.jpgg',
    ],
  },
  {
    id: 'SMXMXMK000044',
    name: 'Mặt dây chuyền bạc đính đá Silver chữ T',
    price: '324.000',
    size: [42],
    status: true,
    trademark: 'PNJSilver',
    main_stone: 'CZ',
    main_color_stone: 'Trắng',
    shape: 'Tròn',
    sex: 0,
    weight: 0,
    description:
      'Hòa theo xu hướng mới của thời đại, thời trang độc đáo của những món đồ trang sức bạc ngày càng đa dạng. Độc đáo và tinh tế trong từng nét chữ, mặt dây chuyền bạc hình chữ của PNJSilver được chế tác bằng chất liệu bạc 925 cao cấp, nhập khẩu từ Ý cùng giá thành hợp lý nên đang được giới trẻ ưa chuộng hiện nay. Đặc biệt, mặt dây được đính đá CZ cao cấp, lấp lánh tạo nên điểm nhấn giúp cho các bạn thêm phần nổi bật.',
    images: [
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/31/smxmxmk000044-mat-day-chuyen-bac-dinh-da-pnjsilver-001.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/38/smxmxmk000044-mat-day-chuyen-bac-dinh-da-pnjsilver-0002.png',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/73/smxmxmk000044-mat-day-chuyen-bac-dinh-da-pnjsilver-04.jpg',
      'https://cdn.pnj.io/images/thumbnails/485/485/detailed/111/smxmxmk000044-mat-day-chuyen-bac-dinh-da-pnjsilver-0004.jpg',
    ],
  },
];

export default products;
